#!/usr/bin/env python3
"""Check markdown links across every mootmaker repo.

Two kinds of link are checked:

1. **Relative links** - resolved against the containing file's directory and checked
   for existence on disk.
2. **Absolute GitHub links into a mootmaker repo** - `https://github.com/<owner>/<repo>/blob/<ref>/<path>`
   and `.../tree/<ref>/<path>`. These are resolved against the *sibling checkout* of that
   repo rather than the network, so the check works offline and catches a path that has
   moved locally but not yet been renamed in the link.

Anchors (`#section`) are stripped before the existence check; anchor *targets* are not
verified, since heading slugs are generated by GitHub and a local check would be a
re-implementation with its own bugs.

Usage:  tools/check-links.py [workspace-root]
Exit:   0 when every link resolves, 1 when any link is broken.
"""

import os
import re
import sys
from pathlib import Path
from urllib.parse import unquote

# Markdown inline links: [text](target). Also catches image links, which share the syntax.
LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
GITHUB_RE = re.compile(
    r"^https://github\.com/(?P<owner>[^/]+)/(?P<repo>[^/]+)"
    r"(?:/(?:blob|tree)/[^/]+/(?P<path>[^#?]*))?"
)
SKIP_DIRS = {".git", "node_modules", "target", "dist", "build", ".terraform", "test-results"}


def repo_checkouts(workspace: Path) -> dict[str, Path]:
    """Map repo name -> local checkout, for every sibling directory that is a git repo."""
    return {
        d.name: d
        for d in sorted(workspace.iterdir())
        if d.is_dir() and (d / ".git").exists()
    }


def markdown_files(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            if name.endswith(".md"):
                yield Path(dirpath) / name


def check_file(md: Path, repo_root: Path, checkouts: dict[str, Path]) -> list[str]:
    problems = []
    try:
        text = md.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError) as exc:
        return [f"{md}: could not read ({exc})"]

    for lineno, line in enumerate(text.splitlines(), 1):
        for target in LINK_RE.findall(line):
            # Strip the anchor; a bare "#anchor" link is same-page and always fine.
            path_part = target.split("#", 1)[0]
            if not path_part:
                continue

            if path_part.startswith(("mailto:", "tel:")):
                continue

            if path_part.startswith("http://") or path_part.startswith("https://"):
                m = GITHUB_RE.match(path_part)
                if not m:
                    continue  # external, not ours to verify
                repo = m.group("repo")
                sub = m.group("path")
                if repo not in checkouts:
                    continue  # not a repo we have locally
                if not sub:
                    continue  # link to the repo itself
                resolved = checkouts[repo] / unquote(sub)
                if not resolved.exists():
                    problems.append(
                        f"{md}:{lineno}: GitHub link to missing path "
                        f"{repo}/{sub}"
                    )
                continue

            # Relative link
            resolved = (md.parent / unquote(path_part)).resolve()
            if not resolved.exists():
                rel = md.relative_to(repo_root) if repo_root in md.parents else md
                problems.append(f"{rel}:{lineno}: broken relative link -> {path_part}")

    return problems


def main() -> int:
    workspace = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    checkouts = repo_checkouts(workspace)
    if not checkouts:
        print(f"No git checkouts found under {workspace}", file=sys.stderr)
        return 1

    all_problems = []
    checked = 0
    for name, root in checkouts.items():
        for md in markdown_files(root):
            checked += 1
            all_problems.extend(check_file(md, root, checkouts))

    for problem in all_problems:
        print(problem)

    print(
        f"\n{checked} markdown files checked across {len(checkouts)} repos; "
        f"{len(all_problems)} broken link(s).",
        file=sys.stderr,
    )
    return 1 if all_problems else 0


if __name__ == "__main__":
    sys.exit(main())
