#!/usr/bin/env python3
"""Check markdown links across every mootmaker repo.

Three kinds of reference are checked:

1. **Relative links** - resolved against the containing file's directory and checked
   for existence on disk.
2. **Absolute GitHub links into a mootmaker repo** - `https://github.com/<owner>/<repo>/blob/<ref>/<path>`
   and `.../tree/<ref>/<path>`. These are resolved against the *sibling checkout* of that
   repo rather than the network, so the check works offline and catches a path that has
   moved locally but not yet been renamed in the link.

3. **Bare-text `<repo>/<path>.md` references in source comments** - things like
   `// mootmaker/docs/reference/use-cases.md, section F` in a `.ts`/`.java`/`.tf`/`.sh`
   file. These are not markdown links, so kinds 1 and 2 never saw them. That gap was
   real: after the 2026-08-29 doc moves this tool reported 0 broken links while 27 such
   references still pointed at pre-move paths, found only by a manual grep (issue #8).
   "0 broken links" giving false confidence at exactly the moment a move makes it matter
   is the thing being fixed.

   **Deliberately limited to `.md` targets.** The issue suggested matching any
   `<repo>/<path>` reference, but that produces false positives on strings that merely
   look like paths - most notably the Terraform state keys (`<environment>/mootmaker-api/
   terraform.tfstate`) that appear throughout the deploy scripts, where the middle segment
   is a repo name and the whole thing is an S3 key, not a file. Documentation references
   are what moved and what this is for, so matching only `.md` keeps it precise. A
   reference inside a URL, or inside markdown link syntax already checked above, is
   skipped rather than reported twice.

Anchors (`#section`) are stripped before the existence check; anchor *targets* are not
verified, since heading slugs are generated by GitHub and a local check would be a
re-implementation with its own bugs.

Usage:  tools/check-links.py [workspace-root]
Exit:   0 when every link resolves, 1 when any link is broken.
"""

import os
import re
import sys
from pathlib import Path
from urllib.parse import unquote

# Markdown inline links: [text](target). Also catches image links, which share the syntax.
LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
GITHUB_RE = re.compile(
    r"^https://github\.com/(?P<owner>[^/]+)/(?P<repo>[^/]+)"
    r"(?:/(?:blob|tree)/[^/]+/(?P<path>[^#?]*))?"
)
SKIP_DIRS = {".git", "node_modules", "target", "dist", "build", ".terraform", "test-results"}

# Files that can carry a bare-text doc reference in a comment. Markdown is included too: a
# reference inside a fenced code block or in prose is just as invisible to LINK_RE.
SOURCE_EXTS = {".md", ".sh", ".java", ".ts", ".tsx", ".tf", ".py", ".yml", ".yaml"}

# A bare `<repo>/<path>.md`, optionally written as `../<repo>/...` - the sibling-checkout form
# every AGENTS.md uses, which resolves to the same workspace path.
#
# The lookbehind alternation is what keeps this off URLs and owner-qualified paths while still
# allowing `../`: in `https://github.com/geoffweatherall/mootmaker/blob/main/x.md` the repo name
# is preceded by `/` and not by `../`, so neither branch matches and it never starts a match.
BARE_RE = re.compile(
    r"(?:(?<=\.\./)|(?<![\w./-]))"
    r"(?P<repo>mootmaker(?:-[a-z0-9-]+)?)/(?P<path>[\w./-]+\.md)"
)
URL_RE = re.compile(r"https?://\S+")


def repo_checkouts(workspace: Path) -> dict[str, Path]:
    """Map repo name -> local checkout, for every sibling directory that is a git repo."""
    return {
        d.name: d
        for d in sorted(workspace.iterdir())
        if d.is_dir() and (d / ".git").exists()
    }


def markdown_files(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            if name.endswith(".md"):
                yield Path(dirpath) / name


def source_files(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            if os.path.splitext(name)[1] in SOURCE_EXTS:
                yield Path(dirpath) / name


def check_bare_refs(src: Path, repo_root: Path, checkouts: dict[str, Path]) -> list[str]:
    """Find bare-text <repo>/<path>.md references that no longer resolve."""
    problems = []
    try:
        text = src.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return []  # binary or unreadable: kind 1/2 already reports unreadable markdown

    for lineno, line in enumerate(text.splitlines(), 1):
        # Spans already handled elsewhere, or not path references at all. Reporting a
        # markdown link twice would be worse than not reporting it here.
        masked = [m.span() for m in URL_RE.finditer(line)]
        masked += [m.span() for m in LINK_RE.finditer(line)]

        for m in BARE_RE.finditer(line):
            if any(start <= m.start() < end for start, end in masked):
                continue
            repo = m.group("repo")
            if repo not in checkouts:
                continue
            target = checkouts[repo] / m.group("path")
            if not target.exists():
                rel = src.relative_to(repo_root) if repo_root in src.parents else src
                problems.append(
                    f"{rel}:{lineno}: bare-text reference to missing path "
                    f"{repo}/{m.group('path')}"
                )
    return problems


def check_file(md: Path, repo_root: Path, checkouts: dict[str, Path]) -> list[str]:
    problems = []
    try:
        text = md.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError) as exc:
        return [f"{md}: could not read ({exc})"]

    for lineno, line in enumerate(text.splitlines(), 1):
        for target in LINK_RE.findall(line):
            # Strip the anchor; a bare "#anchor" link is same-page and always fine.
            path_part = target.split("#", 1)[0]
            if not path_part:
                continue

            if path_part.startswith(("mailto:", "tel:")):
                continue

            if path_part.startswith("http://") or path_part.startswith("https://"):
                m = GITHUB_RE.match(path_part)
                if not m:
                    continue  # external, not ours to verify
                repo = m.group("repo")
                sub = m.group("path")
                if repo not in checkouts:
                    continue  # not a repo we have locally
                if not sub:
                    continue  # link to the repo itself
                resolved = checkouts[repo] / unquote(sub)
                if not resolved.exists():
                    problems.append(
                        f"{md}:{lineno}: GitHub link to missing path "
                        f"{repo}/{sub}"
                    )
                continue

            # Relative link
            resolved = (md.parent / unquote(path_part)).resolve()
            if not resolved.exists():
                rel = md.relative_to(repo_root) if repo_root in md.parents else md
                problems.append(f"{rel}:{lineno}: broken relative link -> {path_part}")

    return problems


def main() -> int:
    workspace = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    checkouts = repo_checkouts(workspace)
    if not checkouts:
        print(f"No git checkouts found under {workspace}", file=sys.stderr)
        return 1

    all_problems = []
    checked = 0
    scanned = 0
    for name, root in checkouts.items():
        for md in markdown_files(root):
            checked += 1
            all_problems.extend(check_file(md, root, checkouts))
        for src in source_files(root):
            scanned += 1
            all_problems.extend(check_bare_refs(src, root, checkouts))

    for problem in all_problems:
        print(problem)

    print(
        f"\n{checked} markdown files checked across {len(checkouts)} repos "
        f"({scanned} files also scanned for bare-text doc references); "
        f"{len(all_problems)} broken link(s).",
        file=sys.stderr,
    )
    return 1 if all_problems else 0


if __name__ == "__main__":
    sys.exit(main())
